<?php


namespace Drupal\resolver_decorated_test;


use Drupal\node\Form\NodeDeleteForm;
use Drupal\resolver_decorated_test\Form\MyNodeDeleteForm;

/**
 * Create a decorating ClassResolver to replace 1 class.
 */
class ClassResolverTwo extends ClassResolverBase {

  public function getInstanceFromDefinition($definition) {
    if ($definition === NodeDeleteForm::class) {
      $definition = MyNodeDeleteForm::class;
    }
    return $this->inner->getInstanceFromDefinition($definition); // TODO: Change the autogenerated stub
  }


}